### ISSUE TITLE
 Request for Re-upload of Checkpoint File Link

### ISSUE THREAD

**Issue by myungkyuKoo** [IndigoPurple/EFENet#1]
The Google Drive link for the currently available checkpoint on the repo is inaccessible due to permission issues.
It seems that even Baidu Netdisk is not accessible, despite not being of Chinese nationality.
Could you please re-upload the checkpoint file link?

**Comment by IndigoPurple** [comment]
> The Google Drive link for the currently available checkpoint on the repo is inaccessible due to permission issues. It seems that even Baidu Netdisk is not accessible, despite not being of Chinese nationality. Could you please re-upload the checkpoint file link?

Thank you for your attention to my work. The link has been updated. Please proceed with the download.
